services:
  bot:
    build: .
    container_name: bot
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
