services:
  bot:
    build: .
    container_name: bot
    command: python3.12 exchange/cli.py
    env_file: .env
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data:
    driver: local
